//! Strict, value-free managed-service secret declarations generated by nixcfg.
//!
//! These declarations tell Pharos which service/slot choices exist. They never
//! contain runtime paths, commands, secret values, ciphertext, credentials,
//! permits, or observed delivery/health state.

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

pub const MANAGED_SERVICE_MANIFEST_SCHEMA: &str = "inspr.pharos.managed-service-declarations.v1";
pub const MANAGED_SERVICE_MANIFEST_VERSION: u16 = 1;
pub const MAX_MANAGED_SERVICE_MANIFEST_BYTES: usize = 64 * 1024;
pub const MAX_MANAGED_SERVICES_PER_HOST: usize = 64;
pub const MAX_MANAGED_SECRET_SLOTS_PER_SERVICE: usize = 32;

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ManagedConsumerKind {
    ManagedService,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ManagedRuntimeKind {
    Compose,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ManagedDeliveryKind {
    PrivateEnvFile,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ManagedReloadMethod {
    ComposeRecreate,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ManagedHealthProbe {
    ComposeHealthcheck,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ManagedSecretSource {
    Generated,
    Import,
}

impl ManagedSecretSource {
    fn contract_name(self) -> &'static str {
        match self {
            Self::Generated => "generated",
            Self::Import => "import",
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ManagedServiceManifestV1 {
    pub schema: String,
    pub schema_version: u16,
    pub generated_by: String,
    pub host_ref: String,
    pub declaration_fingerprint: String,
    pub services: Vec<ManagedServiceDeclarationV1>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ManagedServiceDeclarationV1 {
    pub service_ref: String,
    pub safe_label: String,
    pub runtime_kind: ManagedRuntimeKind,
    pub slots: Vec<ManagedSecretSlotDeclarationV1>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ManagedSecretSlotDeclarationV1 {
    pub slot_ref: String,
    pub safe_label: String,
    pub consumer_kind: ManagedConsumerKind,
    pub delivery: ManagedDeliveryDeclarationV1,
    pub reload: ManagedReloadDeclarationV1,
    pub health: ManagedHealthDeclarationV1,
    pub allowed_sources: Vec<ManagedSecretSource>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ManagedDeliveryDeclarationV1 {
    pub kind: ManagedDeliveryKind,
    pub profile_ref: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ManagedReloadDeclarationV1 {
    pub method: ManagedReloadMethod,
    pub profile_ref: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ManagedHealthDeclarationV1 {
    pub probe: ManagedHealthProbe,
    pub profile_ref: String,
}

// Field order in these private DTOs is deliberately lexicographic to match
// Nix's builtins.toJSON canonical bytes. This stays stable even if
// serde_json's preserve_order feature is enabled elsewhere in the workspace.
#[derive(Serialize)]
struct CanonicalFingerprintBody<'a> {
    host_ref: &'a str,
    services: Vec<CanonicalService<'a>>,
}

#[derive(Serialize)]
struct CanonicalService<'a> {
    runtime_kind: ManagedRuntimeKind,
    safe_label: &'a str,
    service_ref: &'a str,
    slots: Vec<CanonicalSlot<'a>>,
}

#[derive(Serialize)]
struct CanonicalSlot<'a> {
    allowed_sources: &'a [ManagedSecretSource],
    consumer_kind: ManagedConsumerKind,
    delivery: &'a ManagedDeliveryDeclarationV1,
    health: &'a ManagedHealthDeclarationV1,
    reload: &'a ManagedReloadDeclarationV1,
    safe_label: &'a str,
    slot_ref: &'a str,
}

impl ManagedServiceManifestV1 {
    pub fn validate_contract(&self) -> Result<(), ManagedServiceManifestError> {
        if self.schema != MANAGED_SERVICE_MANIFEST_SCHEMA {
            return Err(ManagedServiceManifestError::UnsupportedSchema);
        }
        if self.schema_version != MANAGED_SERVICE_MANIFEST_VERSION {
            return Err(ManagedServiceManifestError::UnsupportedVersion);
        }
        if self.generated_by != "nixcfg" {
            return Err(ManagedServiceManifestError::UntrustedProducer);
        }
        validate_ref("host_", &self.host_ref)?;
        validate_ref("decl_", &self.declaration_fingerprint)?;
        if self.services.is_empty() || self.services.len() > MAX_MANAGED_SERVICES_PER_HOST {
            return Err(ManagedServiceManifestError::InvalidServiceCount);
        }

        let mut service_refs = BTreeSet::new();
        let mut slot_refs = BTreeSet::new();
        let mut previous_service_ref: Option<&str> = None;
        for service in &self.services {
            validate_ref("svc_", &service.service_ref)?;
            validate_safe_label(&service.safe_label)?;
            if !service_refs.insert(service.service_ref.as_str()) {
                return Err(ManagedServiceManifestError::DuplicateServiceRef);
            }
            if previous_service_ref.is_some_and(|previous| previous >= service.service_ref.as_str())
            {
                return Err(ManagedServiceManifestError::NonCanonicalOrder);
            }
            previous_service_ref = Some(&service.service_ref);
            if service.slots.is_empty()
                || service.slots.len() > MAX_MANAGED_SECRET_SLOTS_PER_SERVICE
            {
                return Err(ManagedServiceManifestError::InvalidSlotCount);
            }

            let mut previous_slot_ref: Option<&str> = None;
            for slot in &service.slots {
                validate_ref("slot_", &slot.slot_ref)?;
                validate_safe_label(&slot.safe_label)?;
                validate_ref("delivery_", &slot.delivery.profile_ref)?;
                validate_ref("reload_", &slot.reload.profile_ref)?;
                validate_ref("health_", &slot.health.profile_ref)?;
                if !slot_refs.insert(slot.slot_ref.as_str()) {
                    return Err(ManagedServiceManifestError::DuplicateSlotRef);
                }
                if previous_slot_ref.is_some_and(|previous| previous >= slot.slot_ref.as_str()) {
                    return Err(ManagedServiceManifestError::NonCanonicalOrder);
                }
                previous_slot_ref = Some(&slot.slot_ref);
                if slot.allowed_sources.is_empty() || slot.allowed_sources.len() > 2 {
                    return Err(ManagedServiceManifestError::InvalidSourcePolicy);
                }
                let mut previous_source = None;
                for source in &slot.allowed_sources {
                    let source_name = source.contract_name();
                    if previous_source.is_some_and(|previous| previous >= source_name) {
                        return Err(ManagedServiceManifestError::InvalidSourcePolicy);
                    }
                    previous_source = Some(source_name);
                }
            }
        }
        if self.declaration_fingerprint != self.computed_declaration_fingerprint()? {
            return Err(ManagedServiceManifestError::InvalidDeclarationFingerprint);
        }
        Ok(())
    }

    pub fn computed_declaration_fingerprint(&self) -> Result<String, ManagedServiceManifestError> {
        let body = CanonicalFingerprintBody {
            host_ref: &self.host_ref,
            services: self
                .services
                .iter()
                .map(|service| CanonicalService {
                    runtime_kind: service.runtime_kind,
                    safe_label: &service.safe_label,
                    service_ref: &service.service_ref,
                    slots: service
                        .slots
                        .iter()
                        .map(|slot| CanonicalSlot {
                            allowed_sources: &slot.allowed_sources,
                            consumer_kind: slot.consumer_kind,
                            delivery: &slot.delivery,
                            health: &slot.health,
                            reload: &slot.reload,
                            safe_label: &slot.safe_label,
                            slot_ref: &slot.slot_ref,
                        })
                        .collect(),
                })
                .collect(),
        };
        let canonical = serde_json::to_vec(&body)
            .map_err(|_| ManagedServiceManifestError::InvalidDeclarationFingerprint)?;
        Ok(format!("decl_{:x}", Sha256::digest(canonical)))
    }
}

fn validate_ref(prefix: &'static str, value: &str) -> Result<(), ManagedServiceManifestError> {
    if value.len() < prefix.len() + 8
        || value.len() > 96
        || !value.starts_with(prefix)
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
    {
        return Err(ManagedServiceManifestError::InvalidOpaqueRef);
    }
    Ok(())
}

fn validate_safe_label(value: &str) -> Result<(), ManagedServiceManifestError> {
    let unsafe_display = |character: char| {
        character.is_control()
            || (character.is_whitespace() && character != ' ')
            || matches!(
                character,
                '\u{061c}'
                    | '\u{200b}'..='\u{200f}'
                    | '\u{202a}'..='\u{202e}'
                    | '\u{2060}'..='\u{2069}'
                    | '\u{feff}'
            )
    };
    if value.is_empty()
        || value.len() > 120
        || value.trim().len() != value.len()
        || value.chars().any(unsafe_display)
    {
        return Err(ManagedServiceManifestError::UnsafeLabel);
    }
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ManagedServiceManifestError {
    UnsupportedSchema,
    UnsupportedVersion,
    UntrustedProducer,
    InvalidOpaqueRef,
    InvalidDeclarationFingerprint,
    UnsafeLabel,
    InvalidServiceCount,
    InvalidSlotCount,
    DuplicateServiceRef,
    DuplicateSlotRef,
    NonCanonicalOrder,
    InvalidSourcePolicy,
}

impl std::fmt::Display for ManagedServiceManifestError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let reason = match self {
            Self::UnsupportedSchema => "unsupported schema",
            Self::UnsupportedVersion => "unsupported version",
            Self::UntrustedProducer => "untrusted producer",
            Self::InvalidOpaqueRef => "invalid opaque reference",
            Self::InvalidDeclarationFingerprint => "invalid declaration fingerprint",
            Self::UnsafeLabel => "unsafe display label",
            Self::InvalidServiceCount => "invalid service count",
            Self::InvalidSlotCount => "invalid slot count",
            Self::DuplicateServiceRef => "duplicate service reference",
            Self::DuplicateSlotRef => "duplicate slot reference",
            Self::NonCanonicalOrder => "non-canonical declaration order",
            Self::InvalidSourcePolicy => "invalid source policy",
        };
        formatter.write_str(reason)
    }
}

impl std::error::Error for ManagedServiceManifestError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> &'static str {
        include_str!("../../../contracts/managed-service-declarations-v1.json")
    }

    #[test]
    fn canonical_fixture_is_strict_value_free_and_valid() {
        let manifest: ManagedServiceManifestV1 = serde_json::from_str(fixture()).unwrap();
        manifest.validate_contract().unwrap();
        assert_eq!(manifest.services.len(), 1);
        assert_eq!(manifest.services[0].slots.len(), 1);

        let value: serde_json::Value = serde_json::from_str(fixture()).unwrap();
        for forbidden in [
            "secret",
            "value",
            "ciphertext",
            "token",
            "permit",
            "command",
            "path",
            "generation",
            "phase",
            "healthy",
        ] {
            assert!(
                !fixture()
                    .to_ascii_lowercase()
                    .contains(&format!("\"{forbidden}\"")),
                "fixture contains forbidden field {forbidden}"
            );
        }
        assert_eq!(value["generated_by"], "nixcfg");
    }

    #[test]
    fn canonical_fingerprint_matches_nix_and_go_for_html_like_safe_labels() {
        let mut manifest: ManagedServiceManifestV1 = serde_json::from_str(fixture()).unwrap();
        manifest.host_ref = "host_7f94a1c8e912".to_string();
        manifest.services[0].service_ref = "svc_24b7c8f0aa19".to_string();
        manifest.services[0].safe_label = "<Canary & service>".to_string();
        manifest.services[0].slots[0].slot_ref = "slot_d5019e2a7b11".to_string();
        manifest.services[0].slots[0].safe_label = "Admin <password> & token".to_string();
        manifest.services[0].slots[0].delivery.profile_ref = "delivery_2ed71ad75c98".to_string();
        manifest.services[0].slots[0].reload.profile_ref = "reload_5e776ec5d9a1".to_string();
        manifest.services[0].slots[0].health.profile_ref = "health_84c12f390b2a".to_string();
        assert_eq!(
            manifest.computed_declaration_fingerprint().unwrap(),
            "decl_eed42d4f2d389904ad63beb09256db37f38c3435c15b46840faae1ac181b70e4"
        );
    }

    #[test]
    fn rejects_unknown_variants_fields_duplicates_and_unsafe_labels() {
        let mut value: serde_json::Value = serde_json::from_str(fixture()).unwrap();
        value["extra"] = serde_json::json!(true);
        assert!(serde_json::from_value::<ManagedServiceManifestV1>(value).is_err());

        let mut value: serde_json::Value = serde_json::from_str(fixture()).unwrap();
        value["declaration_fingerprint"] = serde_json::json!(
            "decl_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        );
        let manifest: ManagedServiceManifestV1 = serde_json::from_value(value).unwrap();
        assert_eq!(
            manifest.validate_contract(),
            Err(ManagedServiceManifestError::InvalidDeclarationFingerprint)
        );

        let mut value: serde_json::Value = serde_json::from_str(fixture()).unwrap();
        value["services"][0]["runtime_kind"] = serde_json::json!("nixos_unit");
        assert!(serde_json::from_value::<ManagedServiceManifestV1>(value).is_err());

        let mut value: serde_json::Value = serde_json::from_str(fixture()).unwrap();
        let duplicate = value["services"][0]["slots"][0].clone();
        value["services"][0]["slots"]
            .as_array_mut()
            .unwrap()
            .push(duplicate);
        let manifest: ManagedServiceManifestV1 = serde_json::from_value(value).unwrap();
        assert_eq!(
            manifest.validate_contract(),
            Err(ManagedServiceManifestError::DuplicateSlotRef)
        );

        let mut value: serde_json::Value = serde_json::from_str(fixture()).unwrap();
        value["services"][0]["slots"][0]["safe_label"] = serde_json::json!("unsafe\u{202e}label");
        let manifest: ManagedServiceManifestV1 = serde_json::from_value(value).unwrap();
        assert_eq!(
            manifest.validate_contract(),
            Err(ManagedServiceManifestError::UnsafeLabel)
        );
    }
}
